<a href="https://colab.research.google.com/github/Mr-Hackrr/notebook/blob/main/notebooks/day4q1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv(r"/content/ForbesAmericasTopColleges2019.csv")

In [3]:
data.head()

,Rank,Name,City,State,Public/Private,Undergraduate Population,Student Population,Net Price,Average Grant Aid,Total Annual Cost,Alumni Salary,Acceptance Rate,SAT Lower,SAT Upper,ACT Lower,ACT Upper,Website
0,1,Harvard University,Cambridge,MA,Private,13844,31120,14327.0,49870.0,69600,146800.0,5.0,1460.0,1590.0,32.0,35.0,www.harvard.edu
1,2,Stanford University,Stanford,CA,Private,8402,17534,13261.0,50134.0,69109,145200.0,5.0,1390.0,1540.0,32.0,35.0,www.stanford.edu
2,3,Yale University,New Haven,CT,Private,6483,12974,18627.0,50897.0,71290,138300.0,7.0,1460.0,1580.0,32.0,35.0,www.yale.edu
3,4,Massachusetts Institute of Technology,Cambridge,MA,Private,4680,11466,20771.0,43248.0,67430,155200.0,7.0,1490.0,1570.0,33.0,35.0,web.mit.edu
4,5,Princeton University,Princeton,NJ,Private,5659,8273,9327.0,48088.0,66150,139400.0,6.0,1430.0,1570.0,31.0,35.0,www.princeton.edu

In [4]:
df = data.copy()

In [9]:
df.loc[:6,'Name']

0                       Harvard University
1                      Stanford University
2                          Yale University
3    Massachusetts Institute of Technology
4                     Princeton University
5               University of Pennsylvania
6                         Brown University
Name: Name, dtype: object

In [11]:
df.loc[:6,['Name','State','City']]

                                    Name State          City
0                     Harvard University    MA     Cambridge
1                    Stanford University    CA      Stanford
2                        Yale University    CT     New Haven
3  Massachusetts Institute of Technology    MA     Cambridge
4                   Princeton University    NJ     Princeton
5             University of Pennsylvania    PA  Philadelphia
6                       Brown University    RI    Providence

In [14]:
df['State'].unique()

array(['MA', 'CA', 'CT', 'NJ', 'PA', 'RI', 'NC', 'NH', 'NY', 'DC', 'IL',
       'IN', 'MI', 'TX', 'MD', 'ME', 'TN', 'MO', 'VA', 'VT', 'CO', 'MN',
       'GA', 'WA', 'WI', 'FL', 'OH', 'IA', 'UT', 'OR', 'LA', 'SC', 'DE',
       'AL', 'AZ', 'OK', 'NE', 'KY', 'KS', 'AR', 'WY', 'NV', 'MS', 'ND',
       'HI', 'MT', 'SD', 'NM', 'ID', 'WV', 'AK'], dtype=object)

In [15]:
df['State'].nunique()

51

In [16]:
df.head()

,Rank,Name,City,State,Public/Private,Undergraduate Population,Student Population,Net Price,Average Grant Aid,Total Annual Cost,Alumni Salary,Acceptance Rate,SAT Lower,SAT Upper,ACT Lower,ACT Upper,Website
0,1,Harvard University,Cambridge,MA,Private,13844,31120,14327.0,49870.0,69600,146800.0,5.0,1460.0,1590.0,32.0,35.0,www.harvard.edu
1,2,Stanford University,Stanford,CA,Private,8402,17534,13261.0,50134.0,69109,145200.0,5.0,1390.0,1540.0,32.0,35.0,www.stanford.edu
2,3,Yale University,New Haven,CT,Private,6483,12974,18627.0,50897.0,71290,138300.0,7.0,1460.0,1580.0,32.0,35.0,www.yale.edu
3,4,Massachusetts Institute of Technology,Cambridge,MA,Private,4680,11466,20771.0,43248.0,67430,155200.0,7.0,1490.0,1570.0,33.0,35.0,web.mit.edu
4,5,Princeton University,Princeton,NJ,Private,5659,8273,9327.0,48088.0,66150,139400.0,6.0,1430.0,1570.0,31.0,35.0,www.princeton.edu

In [19]:
private_cnt = 0
public_cnt = 0
for i in df['Public/Private']:
  if i == 'Public':
    public_cnt += 1
  elif i == 'Private':
    private_cnt += 1
  else:
    pass

print("Number of public colleges: ",public_cnt)
print("Number of private colleges: ",private_cnt)

Number of public colleges:  250
Number of private colleges:  400

In [21]:
state_list = df['State'].unique()

array(['MA', 'CA', 'CT', 'NJ', 'PA', 'RI', 'NC', 'NH', 'NY', 'DC', 'IL',
       'IN', 'MI', 'TX', 'MD', 'ME', 'TN', 'MO', 'VA', 'VT', 'CO', 'MN',
       'GA', 'WA', 'WI', 'FL', 'OH', 'IA', 'UT', 'OR', 'LA', 'SC', 'DE',
       'AL', 'AZ', 'OK', 'NE', 'KY', 'KS', 'AR', 'WY', 'NV', 'MS', 'ND',
       'HI', 'MT', 'SD', 'NM', 'ID', 'WV', 'AK'], dtype=object)